import React, { useState, useEffect } from "react";

import { Loader, Card, FormField } from "../componenets";

const Home = () => {
  const [loading, SetLoading] = useState(true);
  const [allPosts, SetAllPosts] = useState(null);

  const [searchText, SetSearchText] = useState("abc");
  // const [searchTimeout, SetSearchTimeout] = useState(null);
  // const [searchResult, SetSearchResult] = useState(null);

  return (
    <section className="max-w-7x1 mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[30px]">
          The Community ShowCase
        </h1>
        <p className="mt-2 text-[#666e75] text-[15px] max-w[500px]">
          Browse through a collection of imaginative and visually stunning
          images generated by Dall-E Ai
        </p>
      </div>

      <div className="mt-16">
        <FormField />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-content items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing Resuls for{" "}
                <span className="text-[#222328]">{searchText}</span>:
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3"></div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
